### ISSUE TITLE
Possibly wrong assumption on std::string treating them as utf-8 encoded

### ISSUE THREAD

**Issue by wjiali6** [cnjinhao/nana#255]
Possibly wrong assumption on std::string ,treating them as utf-8 encoded.
The default encoding in Windows system shipped to many asian countries is not utf-8 (gb2312 for chinese for instance ).
Saving '你好' to a text file using  windows notepad then append this word to nana::textbox  after reading this text file using std::readline results unreadable characters  . This is because the data a std::string holds is not necessarily  utf-8 encoded, it is just a bunch of bytes provided by some users, std::string dose not hold any encoding information.You may consider changing nana::textbox implementation along with other std::string related codes.

**Comment by qPCR4vir** [comment]
We had a lot of discussions about this. The resulting decision was that the API nana offer will mainly (and by default - only) utf-8 encoding. When convenient, nana could offer a second possibility, seems as "an advanced" feature. For example, some function could accept or return "a OS - native encoded string" if the programmer really need to avoid too much conversions. 
So, the current solution to your issue is: 
1- to try to find a convenient advanced function in nana, and if not,
2- it is your responsibility to prior to send it to nana convert the text to utf-8.
Alternatively, if you see it is important, you may try to collaborate and propose new functions that will be added to the set of that "advanced", alternative functions to support other encodings. But the current default nana behaviour of accepting utf-8 will probably not change.
(this is my opinion)

**Comment by wjiali6** [comment]
I noticed your using std::wstring/wchar_t all the way down to text_editor, this requires at least three loops 
( for char * s it is six ) on none utf-8 Windows boxs to convert from one ANSI codepage to nana::text_editor's wstring when using Windows' `MultiByteToWideChar` and `WideCharToMultiByte` functions .
Is there any reason why you don't
implement a `textbox& textbox::append(const std::wstring& text, bool at_caret)` member function?
I guess it might be this two reasons:
1. Windows versions shipped to western countries uses utf-8 encoding for UI, then you implement a apppend using std::string with utf-8 encoded not std::wstring;
2. wchar_t uses four bytes on Linux but two on Windows ,this might cause some problems programing with nana;

I myself added a 
textbox& textbox::append(const std::wstring& text, bool at_caret)
{
			internal_scope_guard lock;
			auto editor = get_drawer_trigger().editor();
			if (editor)
			{
				if (at_caret == false)
					editor->move_caret_end(false);

				editor->put(text);

				editor->try_refresh();
				API::update_window(this->handle());
			}
			return *this;
}
to nana::textbox according to your's   textbox::append and it seems working great;

**Comment by qPCR4vir** [comment]
https://github.com/cnjinhao/nana/issues/42

**Comment by cnjinhao** [comment]
Hi, @wjiali6 
>wchar_t uses four bytes on Linux but two on Windows ,this might cause some problems programing with nana;

Generally the `wchar_t` works fine both on Windows and Linux. As you mentioned, a character(unicode) which length is larger than 2 bytes can be rendered correctly.

>Is there any reason why you don't
implement a textbox& textbox::append(const std::wstring& text, bool at_caret) member function?

A std::wstring overloading should also be provided. The reason some APIs still don't have std::wstring overloading provided is that ... I forgot to implement it.

Contribution of the `std::wstring` version `append` method is welcome. Looking forward to your pull request.

**Comment by wjiali6** [comment]
I'm going to send a pull request this weekend

**Comment by wjiali6** [comment]
#262
