### ISSUE TITLE
textbox question

### ISSUE THREAD

**Issue by os12** [cnjinhao/nana#306]
I would like to highlight parts of the textbox's content as it is being entered. That is, I have a mini language and a parser that verifies the correctness of input. So, it would be nice to be able to attach colors on the fly and hightlight input mistakes:

1+2+<span style="color:blue">_**foobar**_</span>

Obviously I can provide character ranges and colors.

The questions are:

- What the easiest way to add such a feature?
  - I know there are are keywords, but my input is dynamic
- I would like to execute something like this on every key stroke:
    
    ```cpp
    tbox.clear_formatting()
    auto result = parse_my_language(tbox.widget.caption())
    if (!result.is_valid)
        tbox.highlight(result.error_pos)
    ```

**Comment by 5cript** [comment]
I agree that the textbox needs finer style control for syntax highlighting. Specifically FG/BG Color + (Bold/Italic/Normal) at arbitrary positions.

**Comment by os12** [comment]
I'd like to try adding such a feature. Any pointers as to how it should 
be hacked into the existing code?

**Comment by 5cript** [comment]
I have looked a little into the textbox, but it is quite a complicated component.
If I were to start somewhere, I would look into the existing keyword highlighting and see how that works.

**Comment by 5cript** [comment]
I misunderstood, you asked how such an interface addition to nana::textbox could look like.
**This is a very quick idea out of the top of my head.** Maybe something like:
```
nana::textbox tb /* ... */;
tb.range(3, 7).color(/*...*/).style(/* bold? */);
```
Where range returns a proxy object with more methods to modify the text look, whereas color and style return a reference to the proxy itself. 
But i dont know how the range thing would work with weird characters and utf8 etc. 

Maybe someone proposes something superior.

**Comment by dudztroyer** [comment]
I see a problem with using ranges... What to do when the text update? Should offset the formatting or just hold it there?

I'm in need on the same funcionality, and the current way it is set up, the highlight is kind of bugged... Take a look on my example on the forums: http://nanapro.org/en-us/forum/index.php?u=/topic/554/ggsyntax-highlight-help-and-bug-report

I dont have any clue how to add an custom highlighting options since I didnt take a look yet on the textbox control, but I would suggest some kind of regex. It would add support to custom formatting between simbols(strings and such), to comments(-- in lua, // in c++) and a few other use scenarios.

But like I said, no clue on the implementation.

**Comment by dudztroyer** [comment]
Actually the control offers a function to get the line at position Y and the string starting with offset X. If it returned an "TextboxChild" object with those functions you said @5cript , it would be a good starting point to what we are needing to achieve. 

```
nana::textbox tb /* ... */;
// style if it can be implemented with nana.
tb.getline(3).foreground(/*...*/).background(/*...*/).style(/* bold? */); //Sets the whole line style
tb.getline(3).offset(0, 5).foreground(/*...*/).background(/*...*/).style(/* bold? */); //Sets only that offset
tb.getline(3).caption("value"); // set line value (caption as the same string representaion on other cntrols)
tb.getline(3).caption(); // get the line string
tb.getline(3).offset(start, end); // get other reference to that line but within those bounds
```
