### ISSUE TITLE
Impossible to build with CMake + GNU make on Windows (file name conflict)

### ISSUE THREAD

**Issue by Xeverous** [cnjinhao/nana#433]
The build directory after downloading the library is not empty. This itself is smelly (since CMake doesn't have a clean command many projects simply delete build dir to fully rebuild) (and for other reasons). This is already #268.

But there is a much bigger issue, actually caused by this fact: the build directory already contains `makefile` entry (a directory with sample makefile and a readme). CMake generates `Makefile` file in the root of build directory which does not conflict on UNIX systems but does on Windows because paths are case-insensitive there.

```
nana/
    build/
        makefile/
            makefile
            readme.md
        Makefile (name conflict on Windows)
```

Even more, removing the build directory itself is not an option because main CMakeLists.txt includes other files from the build directory.

Current workaround: remove `nana/build/makefile` directory only.

I strongly suggest to rename `build` directory, it is very likely to have more (undiscovered) conflicts with various build tools.

**Comment by qPCR4vir** [comment]
Hi,
Of course, we could change the name... `build-systems`, or better `projects` , but not `tools `or `scripts` because it will confuse people. Jinhao will decide, here is just my opinion, Some other projects use `build `like nana.

Most people use one of the "projects" provided (CB, make, MSVC). Maybe, someday, when we will know cmake sufficiently well, and the generated project will be better than the hand-tuned we have today, we will generate all the other projects from cmake. (I would not put anything "generated" inside the source directory, only original source, under git). But even then many people will use those generated projects and not cmake self. Anyway, from what we alrready learned: it is not recomended nor it is a good practice to build inside the source. They recomend to build in a "paralell" directory, like cmake-build-nana-debug.

As I understand Pitchfork Layout (PFL) is just someone opinion but not a c++ std proposal (I failed to find that). He said: "5. Build Systems: This document does not mandate any particular build system. " and 2.8. tools/ This directory is not required. The tools/ directory is designated for holding extra scripts and tools related to developing and contributing to the project. For example, turn-key build scripts, linting scripts, code-generation scripts, test scripts, or other tools that may be useful to a project develop. **The contents of this directory should not be relevant to a project consumer.**
For many the VC sln or C::B project are relevant.

>a directory with sample makefile and a readme

I see a just a makefile. What is a sample makefile?

**Comment by qPCR4vir** [comment]
Right now I propose you:

```
mkdir buildme
cd buildme
cmake ..
```

**Comment by Xeverous** [comment]
> What is a sample makefile?

Sample makefile meaning "example makefile".

> As I understand Pitchfork Layout (PFL) is just someone opinion but not a c++ std proposal

It is a proposal or at least aims to establish common set of conventions. See at the top of the document

**Comment by qPCR4vir** [comment]
Ok. This is not an "example makefile", this is just nana "oficial" makefile. Make a PR if you have a way to improve it.
Ok. To me a proposal is a document here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/. And to take it "seriously" it need to have positive reviews by the committee.

**Comment by Xeverous** [comment]
I have no incentive to make a PR for that makefile (I'm not very skilled with them). I'm using CMake to generate one instead (easier to configure and customize). The only problem was the name conflict in the build directory. I only ask to rename it.

**Comment by qPCR4vir** [comment]
Ok, maybe I'm missing something: what exactly stop you of building in `build_d` or `build_r` instead of `build`? or better:

```
mkdir ../cmake-build-nana
cd ../cmake-build-nana
cmake ../nana 
```

**Comment by Xeverous** [comment]
Absolutely nothing. It's just the most common convention to build in the `build` directory when using CMake. The solution to this issue is the same as for #268

**Comment by qPCR4vir** [comment]
> Absolutely nothing.

Ok. Low priority: changing that name may break something else - somebody will need to check very well.

**Comment by Xeverous** [comment]
So ... FYI this will be broken because the code uses `build` directory name directly:

https://github.com/cnjinhao/nana/blob/ffa170b5f560dbf899030bdeb0e539aa95b03649/CMakeLists.txt#L128-L139

**Comment by qPCR4vir** [comment]
exactly, and others projects and solutions may hard coded it too

**Comment by qPCR4vir** [comment]
duplicate #268
