### ISSUE TITLE
remove include/nana/config.hpp from git?

### ISSUE THREAD

**Issue by htzh** [cnjinhao/nana#79]
Is ```include/nana/config.hpp``` computer generated? If so it should be removed from git repo and added to the gitignore. My machine generates a different one after the build and shows up in ```git status``` as modified.

On a related note, is there a reason why fixes are not merged into master right away? I understand new features may go into a development branch first but I don't understand why fixes for the master are not on the master right away. If a new user downloads the repo and tries to build he could run into the same problem again unless he knows to check out the hotfix branch instead, which is unlikely. If you want to have versioned releases I suppose you can always create named tags for the corresponding commits.

**Comment by cnjinhao** [comment]
This file defines default configurations, the library can be built by using project solution coming with the repo. If you use CMake to generate a new solution/makefile, it will be overwritten by the CMake generated one.

Master branch always keeps the status of the latest release. Some fixes may be deprecated in next release due to big improvement of feature in other branch. This method can make thing easier to maintain the repo.

**Comment by htzh** [comment]
Is there a way to make ```config.hpp`` not show up in my ```git status```? It would be nice to be able to do ```git add .``` without adding ```config.hpp```.

I still think it is easier if fixes to master are merged into master right away. Reading the mail list I can already see a few cases where people are reporting issues that were fixed in the hotfix branch already, including issue #77 reported by me. Are you concerned about the merge when you merge with a development branch off the release commit? Would git rebase help in that case? You can use rebase to always keep a linearized history in master. See [the workflow here](http://www.cs.cmu.edu/~soonhok/talks/20140519_Git/#/sec-8) which I know worked well.
